services:
  postgres:
    image: postgres:16-alpine
    container_name: book-library-db
    environment:
      POSTGRES_DB: book_library
      POSTGRES_USER: bookuser
      POSTGRES_PASSWORD: bookpass
    ports:
      - "5832:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: