# ---- SCALARS ----
scalar Date

# ---- TYPES ----

type Book {
    id: ID!
    title: String!
    isbn: String!
    publishedDate: Date
    synopsis: String
    author: Author!
    genre: Genre!
    createdAt: Date
}

type Author {
    id: ID!
    firstName: String!
    lastName: String!
    bio: String
    books: [Book!]!
}

type Genre {
    id: ID!
    name: String!
    books: [Book!]!
}

# ---- QUERIES ----

type Query {
    # Books
    books(filter: BookFilterInput): [Book!]!   # <- agrega el argumento
    bookById(id: ID!): Book
    booksByGenre(genreId: ID!): [Book!]!
    booksConnection(first: Int, after: String, last: Int, before: String): BooksConnection!

    # Authors
    authors: [Author!]!
    authorById(id: ID!): Author

    # Genres
    genres: [Genre!]!
}

# ---- INPUTS ----

input CreateBookInput {
    title: String!
    isbn: String!
    publishedDate: Date
    synopsis: String
    authorId: ID!
    genreId: ID!
}

input CreateAuthorInput {
    firstName: String!
    lastName: String!
    bio: String
}

input CreateGenreInput {
    name: String!
}

# ---- MUTATIONS ----

type Mutation {
    createBook(input: CreateBookInput!): Book!
    createAuthor(input: CreateAuthorInput!): Author!
    createGenre(input: CreateGenreInput!): Genre!
    deleteBook(id: ID!): Boolean!
    register(input: RegisterInput!): AuthPayload!   # ← nuevo
    login(input: LoginInput!): AuthPayload!         # ← nuevo
}

# Agrega este input al final del archivo
input BookFilterInput {
    title: String
    authorId: ID
    genreId: ID
}

# --- PAGINATION TYPES ---

type BookEdge {
    node: Book!
    cursor: String!
}

type PageInfo {
    hasNextPage: Boolean!
    hasPreviousPage: Boolean!
    startCursor: String
    endCursor: String
}

type BooksConnection {
    edges: [BookEdge!]!
    pageInfo: PageInfo!
}

# ---- AUTH TYPES ----

type AuthPayload {
    token: String!
    username: String!
}

input RegisterInput {
    username: String!
    password: String!
}

input LoginInput {
    username: String!
    password: String!
}