# Application
spring.application.name=book-library
server.port=8090

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5832/book_library
spring.datasource.username=bookuser
spring.datasource.password=bookpass

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.jpa.open-in-view=false